#!/usr/bin/env bash
# a Bash script that configures a new Ubuntu machine to respect above requirements and install nginx on the server

# installing nginx
sudo apt-get update
sudo apt-get install nginx -y
sudo ufw "Nginx HTTP"

# 
echo "Hello World!" | sudo tee /var/www/html/index.html
# Testing the nginx configuration for error
sudo nginx -t
# restarting the server
sudo service nginx restart
