#!/usr/bin/env bash
# This Script amends the nginx config file to include a custom
# header called X-Served-By
# Install Nginx with the following configurations:
# 	listens on port 80
# 	returns a page containing "Hello World" when queried
#	 at root with a curl GET request.
#	Configures /redirect_me as "301 Moved Permanently".
#	Includes a custom 404 page containing "Ceci n'est pas une page".
#	Contains a custom HTTP header named X-Served-By.
#	The value of the HTTP header is the hostname of the running server.


sudo apt-get update
sudo apt-get install -y nginx
mkdir -p /var/www/html
echo "Hello World" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

printf %s "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	add_header X-Served-By $HOSTNAME;
	root   /var/www/html;
	index  index.html index.htm;

	location /redirect_me {
		return 301 https://www.github.com/favour02/;
	}

	error_page 404 /404.html;
	location /404 {
		root /var/www/html;
		internal;
	}
}" > /etc/nginx/sites-available/default



# sed -i '/http {/a\\tserver {\n\t\tlisten 80;\n\t\tlocation / {\n\t\t\tadd_header X-Served-By "211766-web-02";\n\t\t}\n\t}\n' /etc/nginx/nginx.conf

sudo nginx -t
sudo service nginx restart
