#!/usr/bin/env bash
# A Script that displays the time for 12 hours and 59 minutes
i=0
while (( "$i" < 13 ))
do
	echo "Hour: $i"
	n=1
	while (( "$n" < 60 ))
	do
		echo "$n"
		((n++))
	done
	((i++))
done
